### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by zaz**
It seems you refactored at the same time I did. Sorry for the pain >.< I don't even know how we're going to merge this now. Perhaps I will have time to go through the whole thing and manually rebase if need be.

Anyway, here's an outline of the changes:

  -  Refactor `lib/todos.coffee`: -58 lines, clearer
  -  Formatting changes and small fixes to the readme
  -  Simplify licensing: One file for each license, license name at the top of each file
  -  Set date format to standard `YYYY:MM:DD HH:MM`; allow user to change it
  -  Cleanup snippets
  -  Remove unused audio files

### CODE REVIEW

**Comment by giampierod** [comment]
Thank you so much for doing this Zaz, I might have to go through the changes 1 by 1 to incorporate them.

**Comment by zaz** [comment]
No problem. If you have any questions, just let me know.

I'm planning on making more contributions at some point; I just had to refactor it first because I don't have much experience with programming, and I find refactoring helps me understand a codebase. Some ideas I have are:

  -  Changing the extension from `.GPD` to `.gpd` to match almost all other extensions
  -  Some kind of calendar support (maybe we could start by e.g. highlighting dates that are tomorrow in orange, and dates that are today in red)
  -  For things like `vim-mode`, enter insert mode when I create a new todo (I'm not sure what the best way of doing this would be. We might have to create a package for package interop.)

Maybe we should create a wiki or an issue or something for drafting ideas. Mixing ideas for the project with source code in version control seems odd to me.

**Comment by giampierod** [comment]
Hi Zaz, I merged the request as best as I could. I couldn't take it 1 for 1 because it was really far away from the version I had going. But the spirit of it was the same. 

I changed the extension to .gpd as you suggested. Made sense. This system doesn't use dates for ordering that much, so I don't see a need for a feature like that right now. Maybe in the future. 

I don't use vim-mode. So I am not sure what needs to be done there.

For opening feature requests, just use the github issues feature. 

Some of the things that I need to get done are unit tests. It is a real pain to make a refactoring change like this without a safety net. 

I have a couple of asks for future pull requests:
- Please make smaller groups of changes in the pull requests and push them more frequently. And always pull the latest master and merge your stuff in before creating the pull request. 
-  I am not a fan of "tricky" coding like `fn.call(@) || editor.abortTransaction()`. The intent of this line isn't clear and it actually didn't do what it was supposed to which was `if !fn.call(@) then editor.abortTransaction()`. It took me a while to figure out what was happening and fix this.

**Comment by zaz** [comment]
Thanks. I'll try to keep my repo up-to-date with yours from now on.

I made @22a4de9 because having 2 different date formats were winding me up. What's the reasoning behind using the new configurable date format for closed times, but not for notes?

Sorry, I learnt programming using Bash, where the `fn || fallback` style is the norm (and after learning Lisp, seems very logical). In what situation do `A || B` and `if !A then B` behave differently?

**Comment by giampierod** [comment]
The two different formats are because the note tags are not meant to be human readable dates. It is really an auto-generated ID, but instead of using a GUID I used the current date and time. Even though the note ID is auto-generated, you can manually create it yourself with the `() tag, this also allows for reuse. I could have used a formatted date, but I wanted it to look very "ID" like. I will think about whether the confusion is worth it. Thanks for pointing it out.

As for `A || B` vs. `if !A then B` you are relying on the fact that `||` is a short-circuit operator and that it won't try to run B unless A is false. Clever, but semantically this not what that operator implicitly means and, for some reason, it was causing editor.abortTransaction() to run every time regardless of what happens when A is called. So none of the commands were being completed until I changed it to `if !fn.call(@) then editor.abortTransaction()` (actually, they were completed and then aborted).

**Comment by zaz** [comment]
Ahh, I see.

I don't think the short-circuit operator was causing the issue; in fact, your branch still doesn't work for me. <kbd>Ctrl</kbd> + <kbd>.</kbd> *or* <kbd>}</kbd> *or* <kbd>{</kbd> don't do anything (apart from sometimes scrolling), even after changing `Today` → `Todo` and `Todo` → `Backlog`.

Everything seems to work fine @926d79e before you merged my changes.

**Comment by giampierod** [comment]
Good thing I didn't push a new version out to atom's package manager. This is why I need a test suite. I will need to see what is going on when I get home. I didn't have any issues with the shortcuts before I pushed to github.

**Comment by zaz** [comment]
I'll see if I can fix this:  https://github.com/giampierod/gpd.atom/compare/master...zaz:fix

**Comment by giampierod** [comment]
Zaz. I am not a fan of passing around the editor object. It puts extra
demand on the caller of the function when the function itself can get the
editor pretty easily.

**Comment by zaz** [comment]
It's good practice to get the editor only once because:

 - It makes the function more pure, which makes it easier to reason about and perform tests on.
 - I believe it's possible for the editor to change while a function is running (when someone runs a command, then changes tabs before it has finished). In which case we'd end up making a mess.

Splitting a program into many, small functions with multiple arguments makes for a very beautiful and easy to understand codebase in my opinion. If you're really uncomfortable with passing `editor` though, you could make the `editor` variable inside the `attempt` function global instead. That should avoid problems in case the editor changes.

@2067db4 seems to fix the issue. It looks like there were 2 problems: Moving an item would fail if you didn't specify a prefix, and the `moveTodoToSection` commands must return true, or the move is aborted. A lot of the `editor.` commands that you would assume are truthy are actually falsy.

**Comment by giampierod** [comment]
In @2067db4 what happened to the code that strips the tags? If you are going to merge moveTodoToSection then those methods have to go into `addToBacklog()`. 

You can leave the editor passing, I still don't like it. But I am not going to go to war over it. Maybe we should extend `editor` to add those utility functions in like `SelectLine()`. Then call `getEditor` during `attempt` and pass it to all the other functions.

**Comment by zaz** [comment]
Ohh, sorry. I was thinking that the `moveTodoToBottomOfSection` fn was the same as the `...TopOfSection` one except adding at the bottom. I'll add it back in somewhere.

Sorry to invade your project :(  Good idea! I was thinking the same thing, although I was thinking we should do it in a separate repo if possible because other people might want to use it also, and Git submodules are fairly easy to use.

**Comment by zaz** [comment]
Right. As of @6467f07, everything seems to work. There is a minor issue that a repeated item seems to be indented too much and has a trailing space if the time tag was after the text, but I'm sure these can be fixed with `editor.autoIndentSelectedRows` and a regex if need be. Also, we should disable scrolling while these changes are taking place; it seems to be scrolling to the bottom of the file when an item is closed, for example.

It turns out that Atom already has a lot of useful commands you can browse hidden under “Extended Methods” in the [API docs](https://atom.io/docs/api/v1.0.0/TextEditor#instance-scan), so extending `TextEditor` probably won't be necessary.

If you wait until tomorrow, I can review this and rebase it to clean things up a bit. Otherwise, just feel free to check it and merge it now.

**Pull request closed without merging**
